include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    flutter_style_todos: false
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
