name: beer_app
description: Beers details app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  animations: ^2.0.7
  auto_route: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  material3_drawer:
    git:
      url: https://github.com/danielgorka/material3_drawer.git
      ref: 1.0.0
  retrofit: ^3.3.1
  rive: ^0.9.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.2
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/