name: beer_app
description: Beers details app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.2
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
